### ISSUE TITLE
Refactor WrapperRunner and Worker to use symfony/process

### ISSUE THREAD

**Issue by chbiel** [brianium/paratest#145]
The WrapperRunner und Worker currently does not work on Windows because the Worker is not OS independent.

This may could be solved by using symfony/process for process handling

Target: Refactor the WrapperRunner depending classes

**Comment by brianium** [comment]
@chbiel thanks for opening the issue and your recent pull request! It would be great if the WrapperRunner could work on Windows too, but the WrapperRunner is so effective because of it's use of   the [stream_select](http://php.net/manual/en/function.stream-select.php) function. This function allows the wrapper runner to get changes on each worker as they become available.

However, Windows handles file descriptors quite a bit differently, so this function cannot be used. The PHP docs for this function say:

> Use of stream_select() on file descriptors returned by proc_open() will fail and return FALSE under Windows.

So I'm not sure the Symfony Process component will help us here.

**Comment by chbiel** [comment]
@brianium I will have a look on it myself and update/close the issue when I have more information if this can work.
my problem is with the normal Runner, that the general bootstrapping is done for each test-class, what is ineffective when you have big bootstraplogic

**Comment by chbiel** [comment]
@brianium ok you are right. It's a windows problem as described here: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365141(v=vs.85).aspx

I will close the ticket at first.
but I need this feature so I will try out some other ideas and will create a pull request if I found a solution.
