### ISSUE TITLE
Doesn't work with PHP7

### ISSUE THREAD

**Issue by aik099** [brianium/paratest#162]
Here is failed build using PHP 7: https://travis-ci.org/qa-tools/qa-tools/jobs/63512286

If I just run plain PHPUnit, then build passes sort of (ignore timeouts): https://travis-ci.org/qa-tools/qa-tools/jobs/63516774

Maybe it's failing because xdebug doesn't work on PHP 7.

**Comment by aik099** [comment]
I think we should ignore coverage CLI options (or coverage phpunit.xml options) when no xdebug is installed. For example PHPUnit shows `The Xdebug extension is not loaded. No code coverage will be generated.` and continues to run tests.

The ParaTest is throwing an exception and does nothing:
```
 [PHP_CodeCoverage_Exception]       
  No code coverage driver available
```
In fact maybe internally PHPUnit catches that PHP_CodeCoverage exception and shows nice message instead.

**Comment by julianseeger** [comment]
Makes sense for the default behavior. But additionally the tests would have to be skipped because they make no sense without xdebug.

**Comment by aik099** [comment]
I hope, that that change would fix Travis CI PHP7 test run.

**Comment by julianseeger** [comment]
The time works for us. It's still failing with PHP7 but now it looks fixable.
Probably related to the changed behavior of RuntimeErrors and Fatals (quick guess...)

https://travis-ci.org/brianium/paratest/jobs/77806863

**Comment by julianseeger** [comment]
Help is appreciated here!
Next week, the final release of PHP7 is on schedule and the functional tests are still failing:
https://travis-ci.org/brianium/paratest/jobs/88874512

Would be nice if someone would find the time to dig in an find out why $proc->getErrorOutput() is empty and fatals result in an exitCode of 2 instead of 1. I'll have to disallow php7 builds to fail in the travis build-matrix on november 12th, which will result in a build-break for the whole build.
