### ISSUE TITLE
Feature request: Pass <php> element in phpunit.xml configuration file to PHPUnit

### ISSUE THREAD

**Issue by fuel-odrais** [brianium/paratest#200]
In my phpunit.xml configuration, I've got the following <php> element:

`<php>
        <ini name="memory_limit" value="768M" />
    </php>`

When running PHPUnit standalone and passing the phpunit.xml config via the --configuration option, the memory limit directive is followed.
When running via paratest and passing the phpunit.xml config via the --configuration option, the memory limit directive is not followed. Instead the standard 128M memory limit is used and I'm running out of memory when compiling code coverage.

Is the php element passed on as-is or is only a limited set of phpunit.xml elements used? From looking at ParaTests\Runners\PHPUnit\Configuration.php, I just see support for the bootstrap attribute and testsuites element.

Any help or insight would be greatly appreciated.

Ostin.

**Comment by michaelbutler** [comment]
I don't 100% agree with this, I ran in to the same problem but solved it with -d parameters when running paratest. I don't think paratest should use the same ini overrides as the PHPUnit sub processes, because it's doing different things. In my case, I want paratest itself to have a lot of memory for code coverage merging, but I want my phpunit sub processes to have small amount of memory.
