### ISSUE TITLE
Tests from one Suite are run in different proccesses

### ISSUE THREAD

**Issue by ostrovanka** [brianium/paratest#220]
Hi all!

i'm experiencing the following problem:
I've got autotests for Magento 2, they are divided in testsuites, each test in suite is located in its own file,

In phpunit.xml suites are defined like this:
```
  <testsuite name="MainMenu">
            <directory suffix="Test.php">tests/app/MainMenu/</directory>
        </testsuite>
        <testsuite name="SocialLogin">
            <directory suffix="Test.php">tests/app/SocialLogin/</directory>
        </testsuite>
```
I'm running tests with the following command:
`vendor\bin\paratest.bat --processes="2" --phpunit vendor\bin\phpunit.bat --configuration .\phpunit.xml`

What I expect to see: tests from each suite are executed in separate process.

What I've got: Tests from one suite are executed in different processes in parallel.

how can I run tests from one suite (even if they are defined each in personal class) in one process?

**Comment by julianseeger** [comment]
I don't think thats implemented.
What you're talking about is per-testsuite-parallelization (discussed [here](https://github.com/brianium/paratest/issues/102) a while ago). 
Afaik paratest only supports per-testcase-, per-testmethod-, and per-dataset-parallelization (without `-f`, with `-f`, `-f` + `--max-batch-size`... in that order).

Do you have inter test dependencies?
Then `@depends` should work to make one testmethod depend on another and make them execute in the same process. ("Should" because I have never used or seen them between different Classes.)

**Comment by ostrovanka** [comment]
@julianseeger Thank you for your answer. You're right, paratest can't help me with parallel execution of testsuites.
I solved this problem with running my tests via ant builder.

I'm closing the question.
