### ISSUE TITLE
Parallel tests slower than regular phpunit

### ISSUE THREAD

**Issue by adrianmiu** [brianium/paratest#230]
I'm running paratest in vagrant and they take longer than regular phpunit. I've tried 2, 4, 8, 16 processes. I also tried using `-f` with no avail.

Any suggestions?

**Comment by michaelbutler** [comment]
1. How many CPUs are you allowing the Vagrant VM to use? If using the default (`1`) you likely won't gain anything since only 1 process will truly be running at the same time. In general, the `p` parameter for paratest should match the number of CPU cores you have available.
2. What are your result timings? Are we talking about a difference of 1 second vs 8 seconds or 1 minute vs 8 minutes? The reason I ask is since `paratest` will not always be faster than regular phpunit in 1 process, depending on what your tests are doing and how many there are. There **is** some overhead in bootstrapping & cleaning up paratest processes.
3. Have you tried the `--runner=WrapperRunner` option, it super charges running tests in parallel. This works best with well written tests that have proper setUp and tearDown, and not a lot of static/global/side effects in the code.

**Comment by adrianmiu** [comment]
Thanks `--runner=WrapperRunner` fixed the issue

BTW, I had 2 cpus and the difference was from 9 minutes to 9:30 minutes
