### ISSUE TITLE
Paratest should support multiple classes with different names in one phpunit test file, when only one file is a TestCase

### ISSUE THREAD

**Issue by TysonAndre** [brianium/paratest#240]
PHPUnit can properly handle this case without crashing.
Paratest should as well. **Thoughts?**

In several files in a project I work on,
there are helper classes alongside the test file,
used only in that test file.

- The naming convention used is different, FileNameTest.php contains namespace_subnamespace_FileNameTest extending test case class

I implemented this on a fork already at https://github.com/TysonAndre/paratest/pull/1

- depends on https://github.com/brianium/paratest/pull/237
- Can a branch for v0 be created to create a backport PR against?
- Want to see

**Comment by julianseeger** [comment]
> PHPUnit can properly handle this case without crashing.
Paratest should as well. Thoughts?

I would say it wouldn't harm if it could and it might be good to behave as similar to PHPUnit as possible - but `should` ... I wouldn't sign that. IMHO psr0 and psr4 imply a 1:1 mapping of files and classes. Loosing this restriction for tests then leads to lower quality standards on tests than for the rest of the code, which shouldn't be ... but that opinion might well be java biased. At the end, people should be able to run their existing suites with paratest as a drop-in-replacement for phpunit (well not a replacement but you get the point ^^) which is then a point for the *should* part.

> The naming convention used is different, FileNameTest.php contains namespace_subnamespace_FileNameTest extending test case class

Paratests readme says it expects PSR-0. Everything else has a couple of implications and considering the fact that php has real namespaces since 5.3 you should be able to "upgrade" that project, shouldn't you?
If it works in your PR, it's fine, but I don't think we need extra efforts to support pre php5.3 code

> I implemented this on a fork already at TysonAndre#1
depends on #237
Can a branch for v0 be created to create a backport PR against?
Want to see

? currently, you can create that "backport" PR against the master. Before a merge is made that drops phpunit5 support a phpunit5-branch needs to be created. But until then, just point to master. Or do you fear too many merge conflicts with #237 ?

**Comment by julianseeger** [comment]
fixed with https://github.com/brianium/paratest/pull/241
