### ISSUE TITLE
Need support for explicit test specification with <file> in phpunit configuration file

### ISSUE THREAD

**Issue by tejuprasad** [brianium/paratest#80]
I should be able to run multiple test suites where the order of tests is explicit as specified in 
http://phpunit.de/manual/current/en/organizing-tests.html#organizing-tests.xml-configuration

**Comment by julianseeger** [comment]
As I mentioned in https://github.com/brianium/paratest/pull/144 , I don't think that it makes sense to have explicit orders for tests when you want to run them in parallel. In fact, it could harm if someone wants to compose a testsuite out of specific files, uses paratest to run them in parallel and then recognizes that they run in sequence.
Any other opinions ? maybe @brianium ?

**Comment by brianium** [comment]
Yeah, I think if your tests need to run in order, then they cannot be run concurrently. I am guessing the order matters due to dependencies between the tests?

This would indicate a testing scenario that is simply not a good candidate for concurrent execution. PHPUnit by itself would make more sense in this scenario. @tejuprasad if you have any suggestions for how this could work, pull requests are always welcome :)

**Comment by tejuprasad** [comment]
Thanks for the response! I did exactly what you suggested and used PHPUnit to run test suites, kicking off multiple processes in parallel.
